name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-rabbitmq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Integration tests with rabbitmq
        run: make test
